packages:
  - packages/*
  - sites/*
  - examples/*

catalog:
  "@types/express": ^5.0.3
  "@types/node": 24.3.0
  "@types/ws": ^8.18.1
  concurrently: ^9.2.0
  express: ^5.1.0
  get-port: ^7.1.0
  pino: ^9.9.0
  pino-pretty: ^13.1.1
  rimraf: ^6.0.1
  typescript: ^5.9.2
  uuid: ^11.1.0
  vitest: ^3.2.4
  ws: ^8.18.3
