name: Find all examples packages
description: Discovers all directories in the examples directory and formats them as JSON

outputs:
  examples:
    description: List of example directories
    value: ${{ steps.get-examples.outputs.directories }}

runs:
  using: composite
  steps:
    - name: Get example directories
      shell: bash
      id: get-examples
      run: |
        # Find all directories in the examples folder and format as JSON
        find ./examples -mindepth 1 -maxdepth 1 -type d -print | sed "s|./examples/||" | jq -R . | jq -s . > matrix.json
        DIRECTORIES=$(cat matrix.json)
        rm ./matrix.json
        echo "directories=$DIRECTORIES" >> $GITHUB_OUTPUT
